# Generated by Django 5.2.16 on 2026-08-02 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("companies", "0003_row_level_security"),
        ("procurement", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.item",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="procurement.purchaseorder",
            ),
        ),
    ]
