# Generated by Django 5.2.16 on 2026-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
