# Generated by Django 5.2.16 on 2026-08-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("procurement", "0008_row_level_security_purchase_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("debit_note_number", models.CharField(blank=True, max_length=32)),
                ("amount_cents", models.BigIntegerField()),
                ("tax_amount_cents", models.BigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="procurement.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_returns",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "debit_note_number"),
                        name="unique_company_debit_note_number",
                    )
                ],
            },
        ),
    ]
