# Generated by Django 5.2.16 on 2026-08-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouses",
                to="branches.branch",
            ),
        ),
    ]
