# Generated by Django 5.2.16 on 2026-08-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("inventory", "0005_row_level_security_stock_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_locations",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "storage_locations",
                "ordering": ["warehouse_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="inventory.storagelocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "name"), name="unique_warehouse_location_name"
            ),
        ),
    ]
