# Generated by Django 5.2.16 on 2026-08-28 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_row_level_security"),
        ("companies", "0003_row_level_security"),
        ("hr", "0009_row_level_security_attendance_shift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The platform account this employee record belongs to, if any — links this record to Employee Self-Service. Set by HR, not the employee themselves.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("company", "user"), name="unique_company_employee_user"
            ),
        ),
    ]
