# Generated by Django 5.2.16 on 2026-08-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0011_employee_address_employee_bank_account_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("base_salary_cents", models.BigIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "salary_structures",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="salary_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.salarystructure",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_company_salary_structure_name"
            ),
        ),
    ]
