# Generated by Django 5.2.16 on 2026-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_row_level_security_salary_structures"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="default_days_per_year",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
