# Generated by Django 5.2.16 on 2026-08-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0014_leavetype_default_days_per_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("resignation", "Resignation"),
                            ("termination", "Termination"),
                            ("retirement", "Retirement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("resignation_date", models.DateField()),
                ("last_working_day", models.DateField()),
                ("exit_interview_notes", models.TextField(blank=True)),
                ("clearance_it", models.BooleanField(default=False)),
                ("clearance_finance", models.BooleanField(default=False)),
                ("clearance_admin", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offboarding",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_offboarding",
            },
        ),
    ]
