# Generated by Django 5.2.16 on 2026-08-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0016_row_level_security_offboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id_card", "ID Card"),
                            ("passport", "Passport"),
                            ("contract", "Contract"),
                            ("certificate", "Certificate"),
                            ("work_permit", "Work Permit"),
                            ("health_check", "Health Check"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
