# Generated by Django 5.2.16 on 2026-08-28 15:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0020_row_level_security_shift_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="accrual_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="accrual_rate_days_per_month",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="carryover_cap_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "hr_public_holidays",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "date"),
                        name="unique_company_public_holiday_date",
                    )
                ],
            },
        ),
    ]
