# Generated by Django 5.2.16 on 2026-08-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_row_level_security"),
        ("companies", "0003_row_level_security"),
        ("crm", "0002_row_level_security"),
        ("hotel", "0003_alter_foliocharge_source_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate"),
                            ("wedding", "Wedding"),
                            ("other", "Other"),
                        ],
                        default="corporate",
                        max_length=16,
                    ),
                ),
                (
                    "seating_plan",
                    models.CharField(
                        choices=[
                            ("theater", "Theater"),
                            ("classroom", "Classroom"),
                            ("banquet", "Banquet"),
                            ("u_shape", "U-shape"),
                            ("boardroom", "Boardroom"),
                        ],
                        default="theater",
                        max_length=16,
                    ),
                ),
                ("attendees", models.PositiveIntegerField(default=1)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("charged_to_room", "Charged to room"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=32)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_bookings",
                        to="crm.customer",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_bookings",
                        to="hotel.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "conference_bookings",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceBookingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_cents", models.BigIntegerField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="conference.conferencebooking",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "db_table": "conference_booking_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("day_rate_cents", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "conference_halls",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="conferencebooking",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="conference.conferencehall",
            ),
        ),
        migrations.AddConstraint(
            model_name="conferencehall",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_company_conference_hall_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="conferencebooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="conference_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="conferencebooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("company", "receipt_number"),
                name="unique_company_conference_receipt_number",
            ),
        ),
    ]
