# Generated by Django 5.2.16 on 2026-08-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "number_sequences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "code"), name="unique_company_sequence"
                    )
                ],
            },
        ),
    ]
