# Generated by Django 5.2.16 on 2026-08-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0003_row_level_security"),
        ("procurement", "0004_bill"),
        ("sales", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="procurement.bill",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_company_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role__isnull", False)),
                fields=("company", "role"),
                name="unique_company_account_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit_cents", 0), ("debit_cents__gt", 0)),
                    models.Q(("credit_cents__gt", 0), ("debit_cents", 0)),
                    _connector="OR",
                ),
                name="journal_line_debit_xor_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("bill__isnull", True), ("invoice__isnull", False)),
                    models.Q(("bill__isnull", False), ("invoice__isnull", True)),
                    _connector="OR",
                ),
                name="payment_exactly_one_of_invoice_or_bill",
            ),
        ),
    ]
