# Generated by Django 5.2.16 on 2026-08-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_row_level_security"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_exactly_one_of_invoice_or_bill",
        ),
    ]
