# Generated by Django 5.2.16 on 2026-08-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_remove_payment_payment_exactly_one_of_invoice_or_bill"),
        ("companies", "0003_row_level_security"),
        ("expenses", "0001_initial"),
        ("procurement", "0006_alter_purchaseorder_status"),
        ("sales", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="expenses.expense",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="direction",
            field=models.CharField(
                choices=[
                    ("received", "Received (from a customer)"),
                    ("paid", "Paid (to a supplier or employee)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bill__isnull", True),
                        ("expense__isnull", True),
                        ("invoice__isnull", False),
                    ),
                    models.Q(
                        ("bill__isnull", False),
                        ("expense__isnull", True),
                        ("invoice__isnull", True),
                    ),
                    models.Q(
                        ("bill__isnull", True),
                        ("expense__isnull", False),
                        ("invoice__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_exactly_one_of_invoice_bill_expense",
            ),
        ),
    ]
