# Generated by Django 5.2.16 on 2026-08-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_payment_expense_alter_payment_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
