# Generated by Django 5.2.16 on 2026-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_account_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("accounts_receivable", "Accounts Receivable"),
                    ("accounts_payable", "Accounts Payable"),
                    ("sales_revenue", "Sales Revenue"),
                    ("tax_payable", "Tax Payable"),
                    ("default_expense", "Default Expense"),
                    ("retained_earnings", "Retained Earnings"),
                    ("depreciation_expense", "Depreciation Expense"),
                    ("accumulated_depreciation", "Accumulated Depreciation"),
                    ("salary_expense", "Salary Expense"),
                    ("pension_expense", "Pension Expense (Employer)"),
                    ("payroll_payable", "Payroll Payable"),
                    ("paye_payable", "PAYE Payable"),
                    ("pension_payable", "Pension Payable"),
                    ("payroll_deductions_payable", "Other Payroll Deductions Payable"),
                    ("employee_loan_receivable", "Employee Loan Receivable"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
