# Generated by Django 5.2.16 on 2026-08-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "cost_centers",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="unique_company_cost_center_name",
                    )
                ],
            },
        ),
    ]
