# Generated by Django 5.2.16 on 2026-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrate",
            name="applies_to_room_charges",
            field=models.BooleanField(default=False),
        ),
    ]
