# Generated by Django 5.2.16 on 2026-08-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foliocharge",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("room", "Room"),
                    ("restaurant", "Restaurant"),
                    ("bar", "Bar"),
                    ("spa", "Spa"),
                    ("laundry", "Laundry"),
                    ("gym", "Gym"),
                    ("conference", "Conference"),
                    ("misc", "Miscellaneous"),
                ],
                max_length=16,
            ),
        ),
    ]
