# Generated by Django 5.2.16 on 2026-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_foliocharge_source_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="foliocharge",
            name="tax_amount_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
