# Generated by Django 5.2.16 on 2026-08-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_travel_agency_and_guest_fields"),
        ("hotel", "0004_foliocharge_tax_amount_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="commission_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="travel_agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="crm.travelagency",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("walk_in", "Walk-in"),
                    ("phone", "Phone"),
                    ("travel_agency", "Travel Agency"),
                ],
                default="walk_in",
                max_length=16,
            ),
        ),
    ]
