# Generated by Django 5.2.16 on 2026-08-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("crm", "0006_row_level_security_travel_agencies"),
        ("hotel", "0007_room_transfer_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("walk_in", "Walk-in"),
                    ("phone", "Phone"),
                    ("travel_agency", "Travel Agency"),
                    ("group", "Group Booking"),
                ],
                default="walk_in",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GroupReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_groups",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_group_reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="hotel.groupreservation",
            ),
        ),
    ]
