# Generated by Django 5.2.16 on 2026-08-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0011_seasonal_rate_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="early_checkin_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="late_checkout_approved",
            field=models.BooleanField(default=False),
        ),
    ]
