# Generated by Django 5.2.16 on 2026-08-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_alter_item_tax_rate"),
        ("companies", "0003_row_level_security"),
        ("inventory", "0007_row_level_security_storage_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "output_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boms",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_boms",
                "ordering": ["output_item__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="BOMByproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity_per_unit", models.PositiveIntegerField()),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="byproducts",
                        to="manufacturing.billofmaterial",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_bom_byproducts",
                "ordering": ["item__name"],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity_per_unit", models.PositiveIntegerField()),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.billofmaterial",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "component_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_bom_lines",
                "ordering": ["component_item__name"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "In maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_machines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MachineMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("performed_at", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("cost_cents", models.BigIntegerField(default=0)),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="manufacturing.machine",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_machine_maintenance_logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.CharField(max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                ("produced_quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="manufacturing.billofmaterial",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_production_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost_cents", models.BigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_consumptions",
                        to="manufacturing.productionorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_material_consumptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("rework", "Rework"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="manufacturing.productionorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_quality_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost_cents", models.BigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_entries",
                        to="manufacturing.productionorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_scrap_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("hourly_rate_cents", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_work_centers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="work_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="manufacturing.workcenter",
            ),
        ),
        migrations.CreateModel(
            name="BOMOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("sequence", models.PositiveIntegerField(default=10)),
                (
                    "duration_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="manufacturing.billofmaterial",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.workcenter",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_bom_operations",
                "ordering": ["bom_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("operation_name", models.CharField(max_length=100)),
                ("sequence", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "planned_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="manufacturing.productionorder",
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="manufacturing.workcenter",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_work_orders",
                "ordering": ["production_order_id", "sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="billofmaterial",
            constraint=models.UniqueConstraint(
                fields=("company", "output_item", "name"),
                name="unique_company_bom_output_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="bombyproduct",
            constraint=models.UniqueConstraint(
                fields=("bom", "item"), name="unique_bom_byproduct_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.UniqueConstraint(
                fields=("bom", "component_item"), name="unique_bom_component"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionorder",
            constraint=models.UniqueConstraint(
                fields=("company", "number"),
                name="unique_company_production_order_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="workcenter",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_company_work_center_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_company_machine_name"
            ),
        ),
    ]
