# Generated by Django 5.2.16 on 2026-08-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_row_level_security"),
        ("companies", "0003_row_level_security"),
        ("crm", "0002_row_level_security"),
        ("hotel", "0002_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaundryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guest", "Guest laundry"),
                            ("hotel_linen", "Hotel linen"),
                        ],
                        default="guest",
                        max_length=16,
                    ),
                ),
                (
                    "tracking_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("washing", "Washing"),
                            ("ready", "Ready"),
                            ("delivered", "Delivered"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("charged_to_room", "Charged to room"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=32)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laundry_orders",
                        to="crm.customer",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laundry_orders",
                        to="hotel.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "laundry_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaundryOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_cents", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="laundry.laundryorder",
                    ),
                ),
            ],
            options={
                "db_table": "laundry_order_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="laundryorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("company", "receipt_number"),
                name="unique_company_laundry_receipt_number",
            ),
        ),
    ]
