# Generated by Django 5.2.16 on 2026-08-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_item_barcode"),
        ("companies", "0003_row_level_security"),
        ("crm", "0006_row_level_security_travel_agencies"),
        ("hr", "0024_row_level_security_skills"),
        ("inventory", "0007_row_level_security_storage_locations"),
        ("suppliers", "0002_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("site_address", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("budget_cents", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In progress"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.customer",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "site_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "construction_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("amount_cents", models.BigIntegerField()),
                ("requested_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_orders",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_change_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=32)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                ("unit_cost_cents", models.BigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_items",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_boq_items",
                "ordering": ["category", "description"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.CharField(max_length=20)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("main", "Main contract"),
                            ("subcontract", "Subcontract"),
                        ],
                        default="main",
                        max_length=16,
                    ),
                ),
                ("scope_of_work", models.CharField(blank=True, max_length=255)),
                ("contract_value_cents", models.BigIntegerField(default=0)),
                (
                    "retention_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="construction.constructionproject",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "construction_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=150)),
                ("equipment_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In use"),
                            ("maintenance", "Under maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "construction_equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("daily_rate_cents", models.BigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="construction.equipment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_assignments",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_equipment_assignments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LaborAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("daily_rate_cents", models.BigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_assignments",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_labor_assignments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost_cents", models.BigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_issues",
                        to="construction.constructionproject",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "construction_material_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inspection_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("conditional", "Conditional pass"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_inspections",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_quality_inspections",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SafetyIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("corrective_action", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_incidents",
                        to="construction.constructionproject",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "construction_safety_incidents",
                "ordering": ["-incident_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount_cents", models.BigIntegerField()),
                ("expense_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_site_expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("log_date", models.DateField()),
                ("percent_complete", models.PositiveIntegerField(default=0)),
                ("work_summary", models.TextField(blank=True)),
                ("weather", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_logs",
                        to="construction.constructionproject",
                    ),
                ),
            ],
            options={
                "db_table": "construction_site_logs",
                "ordering": ["-log_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="constructionproject",
            constraint=models.UniqueConstraint(
                fields=("company", "number"),
                name="unique_company_construction_project_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeorder",
            constraint=models.UniqueConstraint(
                fields=("company", "number"), name="unique_company_change_order_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("company", "number"), name="unique_company_contract_number"
            ),
        ),
    ]
