# Generated by Django 5.2.16 on 2026-08-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0009_row_level_security_attendance_shift"),
        ("payroll", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="loan_repayment_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("loan_number", models.CharField(blank=True, max_length=32)),
                ("principal_cents", models.BigIntegerField()),
                ("term_months", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid_off", "Paid off"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "loans",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="payslipline",
            name="source_loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only for a deduction line generated by a Loan repayment installment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repayment_lines",
                to="payroll.loan",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                fields=("company", "loan_number"), name="unique_company_loan_number"
            ),
        ),
    ]
