# Generated by Django 5.2.16 on 2026-08-28 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("payroll", "0004_row_level_security_loans"),
    ]

    operations = [
        migrations.CreateModel(
            name="PensionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_rate_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("7.00"), max_digits=5
                    ),
                ),
                (
                    "employer_rate_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("11.00"), max_digits=5
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_pension_settings",
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lower_bound_cents", models.BigIntegerField()),
                ("upper_bound_cents", models.BigIntegerField(blank=True, null=True)),
                ("rate_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_tax_brackets",
                "ordering": ["lower_bound_cents"],
            },
        ),
    ]
