# Generated by Django 5.2.16 on 2026-08-28 13:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("payroll", "0007_seed_tax_pension_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "standard_hours_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.00"), max_digits=4
                    ),
                ),
                ("working_days_per_month", models.PositiveIntegerField(default=26)),
                (
                    "rate_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.50"), max_digits=4
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_overtime_settings",
            },
        ),
    ]
