# Generated by Django 5.2.16 on 2026-08-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hotel", "0011_seasonal_rate_row_level_security"),
        ("maintenance", "0004_maintenance_schedule_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("furniture", "Furniture"),
                            ("electronics", "Electronics"),
                            ("hvac", "HVAC"),
                            ("kitchen_equipment", "Kitchen Equipment"),
                            ("vehicle", "Vehicle"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("purchase_cost_cents", models.BigIntegerField(blank=True, null=True)),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_service", "In service"),
                            ("under_maintenance", "Under maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="in_service",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="hotel.room",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_assets",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="maintenance.asset",
            ),
        ),
    ]
