# Generated by Django 5.2.16 on 2026-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0008_work_order_part_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="useful_life_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
