# Generated by Django 5.2.16 on 2026-08-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_row_level_security"),
        ("tax", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tax.taxrate",
            ),
        ),
    ]
