# Generated by Django 5.2.16 on 2026-08-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
