# Generated by Django 5.2.16 on 2026-08-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0024_row_level_security_skills"),
        ("recruitment", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="hr.employee",
            ),
        ),
    ]
