# Generated by Django 5.2.16 on 2026-08-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("crm", "0004_row_level_security_new_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="id_documents/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national_id", "National ID"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="TravelAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "commission_rate_percent",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "crm_travel_agencies",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="unique_company_travel_agency_name",
                    )
                ],
            },
        ),
    ]
