# Generated by Django 5.2.16 on 2026-08-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="split_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="split_children",
                to="pos.order",
            ),
        ),
    ]
