# Generated by Django 5.2.16 on 2026-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_happy_hour_promotion_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="is_rush",
            field=models.BooleanField(default=False),
        ),
    ]
