# Generated by Django 5.2.16 on 2026-08-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_orderline_is_rush"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="started_preparing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
