# Generated by Django 5.2.16 on 2026-08-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_row_level_security"),
        ("hr", "0024_row_level_security_skills"),
        ("performance", "0002_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancereview",
            name="rater_type",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("manager", "Manager"),
                    ("peer", "Peer"),
                    ("other", "Other"),
                ],
                default="manager",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_period",
                    models.CharField(
                        help_text='e.g. "2026 Q3" or "H1 2026"', max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "performance_review_cycles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="performancereview",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="performance.reviewcycle",
            ),
        ),
    ]
