# Generated by Django 5.2.16 on 2026-08-24 06:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_tax_rate"),
        ("companies", "0003_row_level_security"),
        ("sales", "0002_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("credit_note_number", models.CharField(blank=True, max_length=32)),
                ("amount_cents", models.BigIntegerField()),
                ("tax_amount_cents", models.BigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "credit_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quotationline",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_percent__lte", 100)),
                name="quotation_line_discount_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_percent__lte", 100)),
                name="sales_order_line_discount_max_100",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes",
                to="sales.invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("company", "credit_note_number"),
                name="unique_company_credit_note_number",
            ),
        ),
    ]
