# Generated by Django 5.2.16 on 2026-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_row_level_security_credit_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="dispatched_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
